### ISSUE TITLE
Passing string to project_names results in broken experience

### ISSUE THREAD

**Issue by miketheman** [ewjoachim/pypitoken#229]
Hey there! I was tinkering with this today, and found a slightly rougher edge than expected.

I made a mistake in not wrapping a `project_names` param in a list, and ended up with a broken object.
Totally my fault, but would have expected a slightly better rejection on this mistake.

```python
>>> import pypitoken
>>> token = pypitoken.Token.load("pypi-<a valid token>")
>>> assert token.restrictions

>>> token.restrict(project_names='example')
<pypitoken.token.Token object at 0x100e402d0>
>>> assert token.restrictions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.11/site-packages/pypitoken/token.py", line 378, in restrictions
    return [
           ^
  File ".../python3.11/site-packages/pypitoken/token.py", line 379, in <listcomp>
    restrictions.Restriction.load_json(caveat=caveat.caveat_id)
  File ".../python3.11/site-packages/pypitoken/restrictions.py", line 174, in load_json
    return cls.load(caveat=caveat_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/pypitoken/restrictions.py", line 155, in load
    raise exceptions.LoaderError(
pypitoken.exceptions.LoaderError: Could not find matching Restriction for [1, 'example']
```

I'd rather expect that the input to `project_names` raise (probably `TypeError`?) if I didn't pass something that could be valid.

**Comment by ewjoachim** [comment]
Hello there !
Hm, an interesting usecase...
I always wonder what we should do in Python lib to account for incorrect types being received (including receiving None when you expect a value). Now that types are explicit, I tend to avoid programming defensively because there's an infinite number of type errors people may do, and it might be complex to test all of them. I'd tend to say that using the code is a way that would have Mypy complain and having unexpected results (instead of a clean failure at the first occasion) is not unexpected. That said, I can understand your frustration.

All that being said, I'm slightly surprised because at the end of the day, `'example'` is an iterable of strings (iterating on individual characters) so I'd expect your code to "work", but add a restriction on project name being one of  `["e", "x", "a", "m", "p", "l", "e"]`. I'll try to see why it doesn't act that way, and I'll come back (hopefully later today)

**Comment by ewjoachim** [comment]
Ok, so the reason this bug looks like that is because while a string is an iterable of chars, JsonSchema maps python strings to json strings and not to a json list of strings (which is very obvious and what we want, but at least we can see where the fork in the road happened).

Also, `project_names` is not typed as an `Iterable[str]` but as a `list[str]`.

What I could totally see myself doing is to loosen types, accept iterables, and cast them as strings. This means that in your case, you'll have a different result:
![image](https://github.com/ewjoachim/pypitoken/assets/1457576/9cee5b97-c1b8-485c-9a8e-19c03ab2c988)
It's still incorrect but it looks more like what Python would do on such cases. The added benefit is that if people mutate the list after creating the Token, the Token will be unaffected (if they did pass a list of strings and not a list of list of strings :D )

Do you think it would be acceptable ? Do you think we should still add defensive code in place ? What would be the extend of the defensive code you'd think is required ? (not saying I'll do it, but I'd love to get more feedback)

**Comment by ewjoachim** [comment]
@miketheman I've made a PR, let's discuss it :)

**Comment by ewjoachim** [comment]
https://pypi.org/project/pypitoken/7.0.1/
